### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by atarsidhu** [atarsidhu/Harman-Sidhu#3]
- [x]  Icons for beds, baths, address etc.
- [x]  Carousel for basic listings
- [x]  Create consistent property image sizes 
- [x]  Add conditional statement if basic listing doesn't have an image
- [x]  Spinner transition
- [x]  Sort By for listings
- [x]  Fade in transitions when scrolling page
